class CreateRadicados < ActiveRecord::Migration[7.0]
  def change
    create_table :radicados do |t|
      t.string :uuid
      t.string :director
      t.bigint :idDirector
      t.string :nombreGrupo
      t.string :nombreGrupo2
      t.string :nombreGrupo3
      t.string :nombreGrupo4
      t.string :razonSocial
      t.bigint :celular
      t.string :correo
      t.string :direccion
      t.string :barrio
      t.string :municipio
      t.string :localidad
      t.string :tparticipacion
      t.string :tparticipacion2
      t.string :tparticipacion3
      t.string :tparticipacion4
      t.string :tparticipacionsas
      t.string :nespectaculo
      t.string :manifestacion
      t.integer :infantil
      t.integer :jovenes
      t.integer :adulto
      t.integer :adulto_mayor
      t.integer :musicos
      t.string :nespectaculo2
      t.string :manifestacion2
      t.integer :infantil2
      t.integer :jovenes2
      t.integer :adulto2
      t.integer :adulto_mayor2
      t.integer :musicos2
      t.string :nespectaculo3
      t.string :manifestacion3
      t.integer :infantil3
      t.integer :jovenes3
      t.integer :adulto3
      t.integer :adulto_mayor3
      t.integer :musicos3
      t.string :nespectaculo4
      t.string :manifestacion4
      t.integer :infantil4
      t.integer :jovenes4
      t.integer :adulto4
      t.integer :adulto_mayor4
      t.integer :musicos4
      t.boolean :transmisionSaberes
      t.boolean :investigaciones
      t.boolean :contenidos
      t.boolean :aporteSalvaguardaOtras
      t.string :cualesSalvaguardia
      t.string :grupoPoblacional
      t.string :grupoEtnico
      t.string :terminosCondiciones
      t.integer :vestuarios
      t.integer :pagomusicos
      t.integer :apoyomovilizacion
      t.integer :otrasInversiones
      t.string :cualesEjecucionDelEstimulo
      t.boolean :lecturabando
      t.boolean :fiestaComparsas
      t.boolean :fiestaDanzasyCumbias
      t.boolean :nocheGuacherna
      t.boolean :SemilleroCarnaval
      t.boolean :CarnavalNiños
      t.boolean :BFVia40
      t.boolean :BFReyMomo
      t.boolean :GPTradiciónFolclor
      t.boolean :GPComparsas
      t.boolean :EncuentroLetanías
      t.boolean :Joselitocenizas
      t.boolean :EncuentroComedias
      t.boolean :FestivalRelacionyEspeciales
      t.boolean :BFSoniaOsorio
      t.boolean :GpCarlosFranco
      t.boolean :ConquistaDelCarnaval
      t.boolean :DesfileCarnavalSurocciente
      t.boolean :LetaniaCumbion
      t.boolean :FarolesTambores
      t.boolean :DesfileSalvaguardiaYNinos
      t.boolean :GuachernaGay
      t.boolean :CoronacionGay
      t.boolean :DesfileCarnavalSuroriente
      t.boolean :DesfileInfantilSurOriente
      t.boolean :OtrosPECarnaval
      t.string :otrosParticipacionEventos
      t.boolean :cedula
      t.boolean :rut
      t.boolean :certificado
      t.boolean :certificacionBancaria
      t.boolean :censo
      t.boolean :evidencias
      t.string :observaciones
      t.string :funcionario

      t.timestamps
    end
  end
end
