class AddColumnsToRadicados < ActiveRecord::Migration[7.0]
  def change
    add_column :radicados, :celular, :bigint
    add_column :radicados, :correo, :string
    add_column :radicados, :direccion, :string
    add_column :radicados, :barrio, :string
    add_column :radicados, :municipio, :string
    add_column :radicados, :localidad, :string
    add_column :radicados, :tparticipacion, :string
    add_column :radicados, :tparticipacionsas, :string
    add_column :radicados, :nespectaculo, :string
    add_column :radicados, :aportesalvaguardia, :string
    add_column :radicados, :transmisionSaberes, :boolean
    add_column :radicados, :investigaciones, :boolean
    add_column :radicados, :contenidos, :boolean
    add_column :radicados, :aporteSalvaguardaOtras, :boolean
    add_column :radicados, :cualesSalvaguardia, :string
    add_column :radicados, :nmiembros, :integer
    add_column :radicados, :nmusicos, :integer
    add_column :radicados, :vestuarios, :integer
    add_column :radicados, :pagomusicos, :integer
    add_column :radicados, :apoyomovilizacion, :integer
    add_column :radicados, :otrasInversiones, :integer
    add_column :radicados, :cualesEjecucionDelEstimulo, :string
    add_column :radicados, :lecturabando, :boolean
    add_column :radicados, :fiestaComparsas, :boolean
    add_column :radicados, :fiestaDanzasyCumbias, :boolean
    add_column :radicados, :nocheGuacherna, :boolean
    add_column :radicados, :SemilleroCarnaval, :boolean
    add_column :radicados, :CarnavalNiños, :boolean
    add_column :radicados, :BFVia40, :boolean
    add_column :radicados, :BFReyMomo, :boolean
    add_column :radicados, :GPTradiciónFolclor, :boolean
    add_column :radicados, :GPComparsas, :boolean
    add_column :radicados, :EncuentroLetanías, :boolean
    add_column :radicados, :Joselitocenizas, :boolean
    add_column :radicados, :EncuentroComedias, :boolean
    add_column :radicados, :FestivalRelacionyEspeciales, :boolean
    add_column :radicados, :Carnavalla44, :boolean
    add_column :radicados, :CarnavalSurOccidente, :boolean
    add_column :radicados, :CarnavalGay, :boolean
    add_column :radicados, :Carnavalla84, :boolean
    add_column :radicados, :CarnavalSurOriente, :boolean
    add_column :radicados, :Disfrazoton, :boolean
    add_column :radicados, :OtrosPECarnaval, :boolean
    add_column :radicados, :otrosParticipacionEventos, :string
    add_column :radicados, :cedula, :boolean
    add_column :radicados, :rut, :boolean
    add_column :radicados, :certificado, :boolean
    add_column :radicados, :certificacionBancaria, :boolean
    add_column :radicados, :censo, :boolean
    add_column :radicados, :evidencias, :boolean
    add_column :radicados, :observaciones, :string
  end
end
